### ISSUE TITLE
Check supported Django versions

### ISSUE THREAD

**Issue by psychok7** [psychok7/django-project-template-yadpt#25]
Check which Django versions we support

**Comment by psychok7** [comment]
@pslobo i tested this and it works for newer versions as well, you can add to the README a requirements section with the following:

```
Python (2.7, 3.2, 3.3, 3.4, 3.5)
Django (1.8, 1.9, 1.10)
```

**Comment by psychok7** [comment]
Well.. after this is merged of course.. https://github.com/psychok7/django-project-template-yadpt/commit/22fed1fb34f20741925a63d772b856859fcdaf1b

**Comment by pslobo** [comment]
Will do. I'll update it tomorrow.
